Добавляет разметку главной страницы
htmlacademy-adaptive/499465-pink-23 pull request #2
Opened 2021-07-27 17:08 UTC by Asya-ya

Пока не придумала как лучше оформить таблицу с тарифами.

2021-07-27 19:04 UTC, 4err requested changes
Отличная работа!

2021-07-27 19:04 UTC, 4err commented on source/index.html
> +            <a class="site-list__link" href="#">Фотографии</a>
Нужно добавить ссылки на наши будущие страницы.

2021-07-27 19:04 UTC, 4err commented on source/index.html
> +        <button class="download__button button" type="button">Скачать приложение</button>
Ссылка же

2021-07-27 19:04 UTC, 4err commented on source/index.html
> +            </a>
А вот это просто изображения доступных ОС приложения.

2021-07-27 19:04 UTC, 4err commented on source/index.html
> +        </div>
Так, ну это точно таблица, поэтому размечать ее следует именно таблицей.

2021-07-29 09:31 UTC, Asya-ya commented on source/index.html
> +            </a>
4.3. Иконки в блоке «Скачать приложение» являются также ссылками и ведут на соответствующие маркеты.

2021-07-29 15:06 UTC, 4err commented on source/index.html
> +            </a>
Аргумент, принято

2021-07-29 15:08 UTC, merged