Module2 task2
htmlacademy-adaptive/499465-pink-23 pull request #3
Opened 2021-07-30 12:59 UTC by Asya-ya

2021-07-30 16:34 UTC, 4err requested changes

2021-07-30 16:34 UTC, 4err commented on source/catalog.html
> +          <li class="photos__item">
Блок фото вполне самостоятелен, поэтому его лучше разместить внутри article, а также создать отдельный бэм блок.

2021-08-02 11:44 UTC, Asya-ya commented on source/catalog.html
> +          <li class="photos__item">
Не очень поняла, у меня блок с фото итак отдельный или имеется ввиду, что конкретно список фото должен быть отдельным блоком? Я сначала обернула сам список в <article>, но ему требуется свой заголовок, который уже используется выше, поэтому я решила просто тег <section> заменить на <article>. Пока не понимаю, что ещё нужно выделить как отдельный блок.

2021-08-02 11:45 UTC, Asya-ya commented on source/catalog.html
> +          <li class="photos__item">
Не очень поняла, у меня блок с фото итак отдельный или имеется ввиду, что конкретно список фото должен быть отдельным блоком? Я сначала обернула сам список в article, но ему требуется свой заголовок, который уже используется выше, поэтому я решила просто тег section заменить на article. Пока не понимаю, что ещё нужно выделить как отдельный блок.

2021-08-02 16:14 UTC, 4err commented on source/catalog.html
> +          <li class="photos__item">
Мы каждую отдельно фотографию можем вырвать из этой страницы и вставить, к примеру, в рекламный блок.  Карточка фото никак не зависит от откружения, она самодостаточна. Такие блоки следует размечать тегом article. Соответственно тебе нужно внутри каждой `li` создать тег `article` и поместить в него текущее содержимое `li`, т.е. всю карточку. 
Опять же т.к. это независимый блок и он может использоваться вне списка, чтоб не тянуть за ним всю систему разметки Бэм блока `photos`, данному article нужно придумать новый бэм блок и всю фотокарточку разметить отталкиваясь от этого бэм блока.

2021-08-02 19:59 UTC, Asya-ya commented on source/catalog.html
> +          <li class="photos__item">
Спасибо, поняла

2021-08-04 07:13 UTC, merged